In [4]:
import pandas as pd
AEX = pd.read_csv('Word_University_Rank_2020.csv')
AEX.head(30)

,Rank_Char,Score_Rank,University,Country,Number_students,Numb_students_per_Staff,International_Students,Percentage_Female,Percentage_Male,Teaching,Research,Citations,Industry_Income,International_Outlook,Score_Result,Overall_Ranking
0,1,1,University of Oxford,United Kingdom,"20,664",11.2,41%,46%,54%,90.5,99.6,98.4,65.5,96.4,95.4,95.40
1,2,2,California Institute of Technology,United States,"2,240",6.4,30%,34%,66%,92.1,97.2,97.9,88.0,82.5,94.5,94.50
2,3,3,University of Cambridge,United Kingdom,"18,978",10.9,37%,47%,53%,91.4,98.7,95.8,59.3,95.0,94.4,94.40
3,4,4,Stanford University,United States,"16,135",7.3,23%,43%,57%,92.8,96.4,99.9,66.2,79.5,94.3,94.30
4,5,5,Massachusetts Institute of Technology,United States,"11,247",8.6,34%,39%,61%,90.5,92.4,99.5,86.9,89.0,93.6,93.60
5,6,6,Princeton University,United States,"7,983",8.1,25%,45%,55%,90.3,96.3,98.8,58.6,81.1,93.2,93.20
6,7,7,Harvard University,United States,"20,823",9.2,24%,49%,51%,89.2,98.6,99.1,47.3,76.3,93.0,93.00
7,8,8,Yale University,United States,"12,402",5.4,20%,50%,50%,92.0,94.8,97.3,52.4,68.7,91.7,91.70
8,9,9,University of Chicago,United States,"13,833",5.7,28%,46%,54%,89.1,91.4,96.7,52.7,76.0,90.2,90.20
9,10,10,Imperial College London,United Kingdom,"16,760",11.7,56%,38%,62%,84.5,87.6,97.0,69.9,97.1,89.8,89.80
10,11,11,University of Pennsylvania,United States,"20,578",6.5,21%,52%,48%,87.5,90.4,98.2,74.0,65.0,89.6,89.60
11,12,12,Johns Hopkins University,United States,"16,171",4.5,26%,52%,48%,81.7,91.4,98.3,91.3,73.2,89.2,89.20
12,13,13,"University of California, Berkeley",United States,"41,081",13.7,17%,50%,50%,83.0,90.6,99.2,46.1,70.4,88.3,88.30
13,13,13,ETH Zurich,Switzerland,"18,956",12.5,39%,32%,68%,81.8,92.8,90.3,56.8,98.2,88.3,88.30
14,15,14,UCL,United Kingdom,"32,665",10.6,52%,57%,43%,77.8,88.7,96.1,42.7,96.2,87.1,87.10
15,16,15,Columbia University,United States,"26,586",5.8,37%,0%,0%,85.6,82.6,98.2,44.8,79.3,87.0,87.00
16,17,16,"University of California, Los Angeles",United States,"41,066",9.4,17%,54%,46%,83.1,88.6,97.3,51.3,64.1,86.8,86.80
17,18,17,University of Toronto,Canada,"73,370",20.1,21%,59%,41%,76.6,89.5,93.6,50.5,84.7,85.5,85.50
18,19,18,Cornell University,United States,"22,319",9.8,25%,49%,51%,79.7,86.0,96.6,37.1,73.4,85.1,85.10
19,20,19,Duke University,United States,"15,309",4.3,19%,49%,51%,82.4,76.8,97.0,99.9,61.5,84.0,84.00
20,21,20,University of Michigan-Ann Arbor,United States,"42,982",8.3,17%,49%,51%,79.4,86.1,94.9,47.7,59.2,83.8,83.80
21,22,21,Northwestern University,United States,"17,951",12.8,20%,49%,51%,74.2,83.8,97.8,78.4,64.1,83.5,83.50
22,23,22,Tsinghua University,China,"38,783",12.0,11%,34%,66%,86.6,94.0,74.6,100.0,47.4,82.6,82.60
23,24,23,Peking University,China,"39,575",11.5,15%,46%,54%,89.1,90.0,73.2,86.6,59.6,82.3,82.30
24,25,24,National University of Singapore,Singapore,"30,869",17.9,28%,51%,49%,76.8,90.4,76.9,58.8,95.5,81.9,81.90
25,26,25,University of Washington,United States,"45,692",11.1,16%,53%,47%,72.2,82.2,98.6,47.5,60.4,81.6,81.60
26,27,26,Carnegie Mellon University,United States,"13,430",13.6,48%,41%,59%,65.9,82.7,98.2,50.5,80.6,81.3,81.30
27,27,26,London School of Economics and Political Science,United Kingdom,"10,570",12.1,71%,53%,47%,69.0,83.0,92.8,35.1,93.2,81.3,81.30
28,29,27,New York University,United States,"44,466",8.9,33%,57%,43%,76.8,77.5,96.5,38.7,65.4,81.1,81.10
29,30,28,University of Edinburgh,United Kingdom,"29,433",12.8,41%,60%,40%,67.3,74.1,96.4,38.9,93.8,79.3,79.40